repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: check-toml
  - id: check-case-conflict
    exclude: ^(.vscode/)
  - id: mixed-line-ending
  - id: debug-statements
  - id: check-added-large-files
    exclude: /static/
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
    exclude: '^\.venv/'

- repo: https://github.com/asottile/pyupgrade
  rev: v2.34.0
  hooks:
  - id: pyupgrade
    args: [--py36-plus]

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: pretty-format-yaml
    args:
    - --autofix
    - --preserve-quotes
    - --indent=2
