repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: check-toml
  - id: check-case-conflict
    exclude: ^(.vscode/)
  - id: mixed-line-ending
  - id: debug-statements
  - id: check-added-large-files
    exclude: /static/
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
    exclude: '^\.venv/'

- repo: https://github.com/asottile/pyupgrade
  rev: v2.34.0
  hooks:
  - id: pyupgrade
    args: [--py36-plus]

- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.1.0
  hooks:
  - id: add-trailing-comma

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: pretty-format-yaml
    args:
    - --autofix
    - --preserve-quotes
    - --indent=2

- repo: local
  hooks:
  - id: black
    name: Format with Black
    entry: black .
    language: system
    types: [python]

  - id: autoflake
    name: autoflake
    entry: autoflake
    language: system
    types: [python]
    args: [-r, --in-place, --remove-all-unused-imports, --remove-duplicate-keys, --remove-unused-variables, .]

  - id: isort
    name: isort
    entry: isort .
    language: system
    types: [python]
    exclude: '^\.venv/'

  - id: flake8
    name: Check with Flake8
    entry: flake8
    language: system
    pass_filenames: false
    types: [python]
    args: [--max-line-length=120, --count, .]

  - id: pylint
    name: Pylint validation
    entry: pylint
    language: system
    types: [python]
    args:
    - --max-line-length=120
    - --disable=missing-function-docstring,missing-module-docstring,missing-class-docstring,no-else-return,too-few-public-methods,import-error
    - --ignore-paths=tests

  - id: mypy
    name: Validate types with MyPy
    entry: mypy
    language: system
    types: [python]
    pass_filenames: false
    args:
    - "."
    - --explicit-package-bases
