name: Tests
on:
  workflow_dispatch:
    inputs:
      parameter:
        description: Force test
  pull_request:
    branches:
    - main

permissions:
  contents: read

concurrency:
  cancel-in-progress: true
  group: "OperationsTax"

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies - pip
      run: |
        python -m pip install --upgrade pip
        curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.4.2 python3 -
    - name: "Set up Python"
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
        cache: 'poetry'

    - name: "Install dependencies - poetry"
      run: |
        poetry install --without code-smells
      env:
        POETRY_VIRTUALENVS_CREATE: true

    - name: Unittest
      run: |
        poetry run coverage run -m unittest -v
        poetry run coverage report
